Mudlet/mudlet-package-repository

.github/workflows/validate-mpackage.yml
Only run validation when a package is changed
See https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
=> Only run validation when a package is changed

packages/shaxamm.mpackage
Reverts Mudlet/mudlet-package-repository#50
no longer supporting git-lfs
=> Revert "Added ShaXAMM 1.0 package"

upload-site/app/components/PackageList.tsx
Use actual filename for the link, instead of inferring it from the package name.
=> Fix package download link in PackageList component

upload-site/app/components/PackageList.tsx
Add a highlight for prominent package authors - the idea is to encourage folks to upload all of the packages they have uploaded to their game forums / websites into `mpkg` as well.
I am not 100% certain on the presentation of the golden author name, but it's a start, let's see how we should evolve this - feedback is welcomed.
=> Add a highlight for prominent package authors

upload-site/app/api/preview/route.ts
Give a better error message for .xml uploads - for more intuitive operation:
=> Give a better error message for .xml uploads

.github/workflows/create-package-index.yml
Needed for https://github.com/Mudlet/mudlet-package-repository/pull/190 which added an icon file - which is being extracted successfully, but not actually committed.
=> Update package index workflow to include icon files in the commit

upload-site/app/lib/packageParser.ts
Fixes https://github.com/Mudlet/mudlet-package-repository/issues/162. Makes the regex pattern only accept `value = [[content]]`, not `value = 'content'` or `value = "content"`.
Ideally we'd [run the Lua interpreter](https://github.com/Mudlet/mudlet-package-repository/blob/main/.github/workflows/validate-mpackage.yml#L108-L109) to get these values, but that seems tricky to do in a pure NodeJS environment.
=> Fix regex pattern in parseConfigLua function not to stop at apostrophes

.github/workflows/create-package-index.yml, reindex.lua
Write the json file and validate it with yajl after every package - this way we can tell if a package breaks yajl before merging it, and know which one did it too.
Related to https://github.com/Mudlet/mudlet-package-repository/issues/159 but doesn't complete solve the problem yet.
=> Fail fast on invalid utf8 in a packge

upload-site/app/lib/packageParser.ts
`created` field extraction broke with https://github.com/Mudlet/mudlet-package-repository/pull/189 - sometimes it comes in this format:
```
created = [[2024-11-26T22:50:47+0000]]
```
And sometimes in this:
```
created = "2025-01-20T00:05:07+08:00"
```
This fixes it to work with both.
Before fix:
After fix:
=> Fix package upload

upload-site/app/api/upload/route.ts, upload-site/app/components/Auth.tsx
Remove user name from package update and signin message - in retrospect, putting folks' names out there is not a good idea.
The original intent was to keep track of bad actors, but we'll think on a better mechanism in the future.
=> Remove user name from package update and signin message

upload-site/app/api/preview/route.ts
Fix icon path in metadata extraction for preview route - now properly works for icons with spaces in them. It was a bit of a fluke that it worked before, really!
=> Fix icon path in metadata extraction for preview route

.github/workflows/create-package-index.yml
Don't rebuild indexes in forks - because that messes up syncronising the fork a bit every time, as both Mudlet repo and the fork have separate commits that are unrelated to each other.
=> Don't rebuild indexes in forks

reindex.lua
Add package count tracking to reindex process - helps us keep track of how many packages are available.
=> Add package count tracking to reindex process

.github/workflows/muddle-mpkg.yml
Same as https://github.com/Mudlet/mudlet-package-repository/pull/209, this prevents forks from "getting ahead" of the mudlet repo, which makes it more difficult to sync:
=> Only muddle mpkg in the main repo

README.md, mpkg/README.md, upload-site/app/components/IntroSection.tsx, upload-site/app/components/PackageList.tsx, upload-site/app/lib/packages.ts, upload-site/app/page.tsx
Remove all mudlet.github.io links - they are no longer so active, and it might help keeping the package count on the homepage fresh.
=> Remove all mudlet.github.io links

upload-site/app/components/PackageList.tsx
@ironcross32 mentioned it is actually triggering too often for him.
=> Remove aria-expanded attribute from PackageList component per player feedback

upload-site/app/components/PackagePreview.tsx
It wasn't being shown before, making it hard to tweak the description to exactly what you'd like.
Now it does this:
=> Enhance PackagePreview component with Markdown support for description

upload-site/app/components/PackagePreview.tsx, upload-site/app/components/UploadForm.tsx
Improve upload form for slow connections - in case you are on a slow connection or uploading a large package, the form would not react at all for a long while. Now, if things are taking longer than expected, it says `Loading preview...`:
[Screencast from 2025-01-26 21-37-17.webm](https://github.com/user-attachments/assets/4cc65e3f-c7ad-4971-a7d8-0a8fbec42f01)
=> Improve upload form for slow connections

reindex.lua
Fixes the icon for # repeat alias not working because `#` needs to be escaped:
=> Add URL encoding for package names in icon file saving

reindex.lua
Fix package count increment logic in reindex.lua - it was counting images and everything else before.
=> Fix package count increment logic in reindex.lua

upload-site/app/components/PackageList.tsx
Changes the sorting from showing all of the upper case ABC's first and the lowercase abc's after to be AaBbCc. 
This is not fixed in stone and might change in the future as we get a better understanding of how to handle sorting.
=> Sort packages in a case-insensitive manner by mpackage

upload-site/app/components/PackageList.tsx, upload-site/app/lib/packages.ts, upload-site/app/lib/types.ts, upload-site/app/page.tsx
'All packages' page functionality unchanged (still sorted alphabetically by mpackage field).
(Also the backend now allows the package list to be sorted by other fields, and for the sort order to be reversed, in case anyone feels like adding controls for that to the frontend.)
| Live website | This PR |
| --- | --- |
| !['recent uploads' on the live website](https://github.com/user-attachments/assets/2e8d3bdb-8a04-4328-ac2a-b380a6bff397) | !['recent uploads' on this version](https://github.com/user-attachments/assets/790188cf-acb0-44c7-a4e6-78d9b40dea1b) |
=> Solving issue #197, front page 'recent uploads' listing is now sorted by upload timestamp.

upload-site/app/components/PackageList.tsx, upload-site/app/globals.css, upload-site/app/page.tsx
Long story short, all of the package divs have a sanitized version of their `mpackage` value as their `id`, and each of these divs has a clickable link on them to themselves (taking advantage of anchor links).
The practical upshot of which being that you can easily obtain and then share a link to a package, like so: <https://packages.mudlet.org/packages#pkg-MUDKIP_Mud2> (or <http://localhost:3000/packages#pkg-MUDKIP_Mud2> if you're running a development build locally).
Current implementation does look a *bit* scuffed (see below screenshot with badly-drawn red circle around a link), but main thing is that it works.
* Improvements that may be worth considering later on (by someone who actually knows what they're doing with frontend stuff)
* Auto-expanding the linked package if a user opens …
=> Implementing #441 via clickable sanitized anchor links
