Mudlet/mudlet-package-repository

reindex.lua
This makes it easier to read through the json file
=> Pretty print package index

.github/workflows/create-package-index.yml, index.html, packages/mpkg.packages.json
=> Fix workflow to use lfs when checking out

README.md
clarify how to submit a package
expand other information
=> Expand README.md instructions.

.github/workflows/muddle-mpkg.yml
not required to run on push requests
=> update workflow to only run on push

mpkg/mfile, mpkg/src/scripts/Mudlet_Package_Manager_CLI.lua
- periodic 12 hours package listing refresh
- silence auto-updates, but allow manual updates to inform user
closes #60
=> add automatic package updating every 12 hours

mpkg/mfile, mpkg/src/scripts/Mudlet_Package_Manager_CLI.lua
don't be in silent mode when calling mpkg upgradeable manually
=> don't be in silent mode when calling mpkg upgradeable manually

upload-site/app/components/UploadForm.tsx
=> Add pull request URL display upon successful package upload

upload-site/app/api/upload/route.ts, upload-site/package-lock.json, upload-site/package.json
See https://github.com/Mudlet/mudlet-package-repository/pull/122 for an example
=> Update PRs with package

upload-site/app/components/UploadForm.tsx
[Screencast from 2025-01-01 12-44-36.webm](https://github.com/user-attachments/assets/70baa545-23c0-42cc-9169-0bac993972e4)
=> Add drag-and-drop functionality to package uploads

upload-site/app/api/preview/route.ts, upload-site/app/components/PackagePreview.tsx, upload-site/app/components/UploadForm.tsx, upload-site/app/lib/types.ts
[Screencast from 2025-01-01 13-34-47.webm](https://github.com/user-attachments/assets/a27c2302-2a6d-4192-8a35-8170ee85de94)
=> Add package validation

upload-site/app/components/UploadForm.tsx
[Screencast from 2025-01-01 13-45-01.webm](https://github.com/user-attachments/assets/dd995322-200a-41d3-86b2-7cb16c0ef32d)
=> Add session validation to the upload component and prompt for sign-in

upload-site/app/components/IntroSection.tsx, upload-site/app/components/Navigation.tsx, upload-site/app/packages/page.tsx, upload-site/app/page.tsx
[Screencast from 2025-01-01 14-13-10.webm](https://github.com/user-attachments/assets/50ed0ba6-cb95-43cb-8b99-45407f3f6852)
=> Add intro and all packages pages

upload-site/app/components/PackageList.tsx, upload-site/package-lock.json, upload-site/package.json, upload-site/tailwind.config.ts
Accessibility and keyboard navigation-friendly, too:
[Screencast from 2025-01-05 17-52-39.webm](https://github.com/user-attachments/assets/fd474dee-a4ba-4e52-8452-85870256d56e)
=> Show package descriptions

upload-site/app/api/upload/route.ts, upload-site/app/lib/github.ts
Delete old packages prior to uploading new ones
Fixes https://github.com/Mudlet/mudlet-package-repository/issues/167
=> Fix duplicate package upload issue

.github/workflows/validate-mpackage.yml
Closes https://github.com/Mudlet/mudlet-package-repository/issues/165
=> Fix duplicates check to work for package updates

upload-site/app/components/IntroSection.tsx, upload-site/app/globals.css
=> Improve intro - less technical & invite folks to upload

.github/workflows/update-core-packages.yml
Send in core package updates one by one, so we obey the "only 1 package update per PR" rule.
=> Send in core package updates one by one

upload-site/app/globals.css
It looks better on mobile without it @dt192 
[Screencast from 2025-01-18 23-00-24.webm](https://github.com/user-attachments/assets/43969194-d7bd-40c5-bd4b-641d29755d26)
=> Remove padding from page content in globals.css

.github/workflows/create-package-index.yml, packages/mpkg.packages.json
See successful run: https://github.com/Mudlet/mudlet-package-repository/actions/runs/12853587424/job/35836940128
=> Fix yajl install in indexing workflow

mpkg/mfile, mpkg/src/scripts/Mudlet_Package_Manager_CLI.lua
whitelisted packages default to version 0, allowing updates
/closes #158
=> whitelist to allow mudlet default package updates to non-versioned ones

upload-site/app/api/upload/route.ts, upload-site/app/components/ProgressBar.tsx, upload-site/app/packages/page.tsx, upload-site/app/page.tsx, upload-site/package-lock.json, upload-site/package.json
closes https://github.com/Mudlet/mudlet-package-repository/issues/220
=> Add 100 packages progressbar
